### ISSUE TITLE
No SPM version numbers?

### ISSUE THREAD

**Issue by SAPIENTechnologies** [migueldeicaza/SwiftTerm#105]
I am trying to add this dependency through Xcode 11, but when I input the URL, there is no version information for the rules. Where do i get that? Pardon my naivte

**Comment by migueldeicaza** [comment]
I do not know, this is news to me too

**Comment by migueldeicaza** [comment]
Closing for not knowing what this is about

**Comment by SAPIENTechnologies** [comment]
When trying to add a swift package through Xcode's FILE->Swift Packages -> Add package Dependency...

These are the values I am talking about. Usually they come in pre-filled with the current version number "up to the next major version." You cannot simply type these in as it will fail with the error "Failed to resolve dependency because no versions of SwiftTerm match the requirement " of whatever version numbers you typed in...

![Screen Shot 2020-05-04 at 8 23 20 AM](https://user-images.githubusercontent.com/15348275/80982845-b5c50480-8de0-11ea-8bb3-45d874c569db.png)

**Comment by migueldeicaza** [comment]
Could you research what is required and submit a PR?

**Comment by SAPIENTechnologies** [comment]
It looks like the author needs to create a release in git and tag that with a semantic version number...

(from https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md)

Publishing a Package

To publish a package, create and push a semantic version tag:

$ git init
$ git add .
$ git remote add origin [github-URL]
$ git commit -m "Initial Commit"
$ git tag 1.0.0
$ git push origin master --tags
Now other packages can depend on version 1.0.0 of this package using the github url. An example of a published package can be found here: https://github.com/apple/example-package-fisheryates
