### ISSUE TITLE
iOS: Custom View to augment the native keyboard with Unix convenience keys

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTerm#116]
This view should be attached to the keyboard and offer some convenient operations:

- [x] escape key
- [x] control key
- [x] arrow keys
- [x] `~`
- [x] `.`
- [x] `-`
- [x] `/`
- [x] tab
- [x] dismiss keyboard
- [x] Mode switcher button
- [ ] Double-tap on ctrl/alt to lock them
- [x] Have an option to show more keys.

DISCUSSION: Should the cursor control be an overlay on top of the terminal, like in video games?

Additional keys that should be shown:
- [x] Fx keys
- [x] PageUp/Down
- [x] Home/End
- [x] Delete
- [x] Insert

Details on how to do this:

https://developer.apple.com/documentation/uikit/uiresponder/1621092-inputview

Now that this is implemented, I really think I need iPhone/iPad versions of this toolbar.

- [x] iPad version of the toolbar
- [x] Probably remove a few commands, to leave space for some key ones like "More" and mode switching.

**Comment by SAPIENTechnologies** [comment]
I have implemented this type of thing using an InputAccessoryView.

**Comment by migueldeicaza** [comment]
I have not managed to get the view in.   The OS is leaving the space aside, but it does not render my view.   Not sure why.

I am pushing to a branch

**Comment by migueldeicaza** [comment]
I might want to try creating a view controller and overriding the inputAccessoryView there, and not in my view:

https://thoughtbot.com/blog/input-accessorizing-uiviewcontroller

**Comment by migueldeicaza** [comment]
Ok it works if you actually call the method that adds the UI elements to the view.  oops
