### ISSUE TITLE
Terminal data parsing incomplete

### ISSUE THREAD

**Issue by JohnnyTseng** [migueldeicaza/SwiftTerm#123]
Hello, thank you for developing this library, I am using this library to parse vt100 data from a bbs site.
However, I've encounter a issue that the result parsed from buffer is incomplete,
I've created a demo project that could reproduce the issue.

Demo project download link, just build and run the terminal on Mac: https://github.com/JohnnyTseng/SwiftTerm

Explanation:

1. In the demo project, I've fed 3 times of buffer text into the terminal (in `MacTerminal` -> `ViewController.swift`)

2. I'd expect row at line 10 should return `https://i.imgur.com/uh2NBHZ.jpg`, however instead it returns `i.imgur.com/uh2NBHZ.jpg` which is a incomplete text, it should contain the `https://`

This is a image with explanation from a normal bbs client 

<img width="1083" alt="Screen Shot 2020-05-15 at 07 50 15" src="https://user-images.githubusercontent.com/2656519/81996851-c1d28100-9680-11ea-9bf6-d84de3d68993.png">

As you can see page 2 row 10 returns complete `https://i.imgur.com/uh2NBHZ.jpg` string,
but when parsing using SwiftTerm library, it only returns `i.imgur.com/uh2NBHZ.jpg`

![Screen Shot 2020-05-15 at 08 04 37](https://user-images.githubusercontent.com/2656519/81997650-019a6800-9683-11ea-8a91-a2b76df0d39b.png)

I'm wondering if it's because row 10 at page 1 also begins with `https://`, and row 10 at page 2 also begins with `https://`
but somehow it failed to add `https://` back at page 2 

I'd be very appreciated if the author could help out with this issue, thank you for developing this amazing library!

**Comment by migueldeicaza** [comment]
Could you try to come up with the minimal test case scenario?

**Comment by JohnnyTseng** [comment]
@migueldeicaza Hello yes, I've already created a reproduce project, 

1. Please clone https://github.com/JohnnyTseng/SwiftTerm
2. On master branch, build and run the app with Mac app 
3. It'll show the wrong result on the Terminal

The reproduce data is in `MacTerminal->ViewController.swift`'s `override func viewDidLoad()` method, I've fed 3 times of text into the terminal, although some text are in Chinese, but I think this wont effect debugging.

If this is not what you expect, please tell me, I'll try my best to provide an example, Thank you

**Comment by migueldeicaza** [comment]
I just do not have time right now to work on this, so I was trying to help you debug the source of the problem.

**Comment by JohnnyTseng** [comment]
Hi @migueldeicaza , it's okay! It'll also be great if you know the root cause, perhaps I could debug by myself, thank you for helping
