### ISSUE TITLE
Integration problem

### ISSUE THREAD

**Issue by SpectralDragon** [migueldeicaza/SwiftTerm#128]
I've troubles with integration terminal view to my project.

1) Terminal view doesn't scrolling
2) In latest master branch I got are ghost glyphs when typing.

![RPReplay_Final1591096399](https://user-images.githubusercontent.com/6003467/83514464-5ee44500-a4dc-11ea-94ea-d768321df730.gif)

Code:

```swift
// Place where I got data from iSH
func terminal(_ terminal: iSHTerminal, didReceive data: Data) {
    DispatchQueue.main.async {
        self.feed(byteArray: [UInt8](data)[...])
    }
}
    
// Place where I passed data to iSH
func send(source: TerminalView, data: ArraySlice<UInt8>) {
    let pointer = data.withUnsafeBytes { $0.bindMemory(to: Int8.self).baseAddress! }
    self.terminal.sendInput(pointer, length: data.count)
}

```

**Comment by SpectralDragon** [comment]
2) was resolved in commit: https://github.com/migueldeicaza/SwiftTerm/commit/33508209801ad2ceecc21b1d8fdffc86eaefa625

**Comment by migueldeicaza** [comment]
Yes, the scrolling on iOS is still a pending task.

Doing a simple but crude scroller is easy.   Doing the right one (where the scrolling is handled by UIScrollView) is going to take me some time, as I need to read up on that.

**Comment by migueldeicaza** [comment]
I am going to close this bug, as scrolling is being tracked in #99
