### ISSUE TITLE
Kill LocalProcess?

### ISSUE THREAD

**Issue by mattschrage** [migueldeicaza/SwiftTerm#132]
First off, thank you for this incredibly cool project. 

I'm trying to kill a long-running interactive `LocalProcess` and can't tell whether this is supported by the current API.

So far, I've attempted:
1. `kill(term.process.shellPid, SIGTERM)`
2.  Send the `^D` exit signal: `term.send(data: [0x4])`

Neither has triggered the exit block I defined when initializing the terminal.
```swift
  let term = HeadlessTerminal { (exit) in
           print("Exit:\(exit)")
  }
```

Any tips?

**Comment by migueldeicaza** [comment]
Hello,

The kill operation is the only reliable one.  Sending control-d will only work if the process happens to be in the shell and the shell is configured to treat control-d as eof (which is the default but could be changed under you)

That said - there is possibly a limitation in the code in raising the notification when the process is killed, I would need to look into it - just a bit hard with the kids on vacation, but will try to look into it

**Comment by mattschrage** [comment]
Thanks for the quick reply. I think the misconfiguration was on my end. I manually set the process delegate on `HeadlessTerminal` which was overwriting the internal implementation. Fixed that and everything seems to be working.
