### ISSUE TITLE
Sixel work

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTerm#141]
Currently the SixelDcsHandler contains AppKit/UIKit/CoreGraphics code that would not be portable outside of Apple.

The SixelDcsHandler needs to deal purely with the image data, and the code that creates CGImages needs to go into the Apple directory;  as well as UIImage/NSImage need to go into the Mac and iOS directories respectively.

ImageData likely should not have a CGImage/TTImage at all, but instead the underlying data.

**Comment by migueldeicaza** [comment]
Windows Terminal has a branch describing their implementation:

https://github.com/skyline75489/terminal/commits/chesterliu/dev/sixel-parser

**Comment by skyline75489** [comment]
Hi there. Saw your reference in the WT repo and figured that I need to clarify my position. I'm a Microsoft employee but I'm NOT part of the WT (or to be exact, the Console) team. I contributed to WT repo as a community member. Please don't think of my work as the implementation of the Console team, as my work may not be endorsed by them.

And by the way, great work on this project. It looks solid 👍 .

**Comment by migueldeicaza** [comment]
No problem!   I just wanted to track the issue, as you might have some interesting tests and discussions that I want to look into.

For example, I do not understand yet how Sixel allocates space for the images, so that is on my list of things to research.

Thanks for getting in touch!

**Comment by migueldeicaza** [comment]
Completed the sixel work
