### ISSUE TITLE
SwiftFormat

### ISSUE THREAD

**Issue by lunixbochs** [migueldeicaza/SwiftTerm#144]
Hi, I'm using SwiftTerm for a project and looking to contribute my improvements upstream.
Would it be okay to standardize on a code formatter like [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) and reformat the repo?

**Comment by migueldeicaza** [comment]
Not likely, I have not spent time learning/using it, so it is not immediately something I would do.

**Comment by migueldeicaza** [comment]
Also, it would make it harder for me to merge my handful of work in progress branches.
