### ISSUE TITLE
Problem Cloning

### ISSUE THREAD

**Issue by frios** [migueldeicaza/SwiftTerm#146]
I have tried to clone this repo through the mac Desktop app and through Xcode but I get an authentication Failure due to the SwiftSH.binaries. How do I get past that. Sorry...Github newbie.

**Comment by frios** [comment]
Problem solved. It was an SSH key issue

**Comment by RyanMorash** [comment]
I'm able to clone the repo normally through both the GitHub Desktop and Xcode, but not through Swift Package Manager within Xcode. Any other Swift packages seem to load fine.
