### ISSUE TITLE
Weird characters when connected to PowerShell via ssh

### ISSUE THREAD

**Issue by frios** [migueldeicaza/SwiftTerm#167]
I am using your iOS terminal to communicate with BASH and Powershell remote servers. When I connect to a BASH session, everything works as expected. But when I connect to a PowerShell session, every time I type something, only garbage characters are displayed. Yet when I press RETURN, the correct command executes. For instance:

I connect to a macOS 11 machine running PowerShell as its default shell. I get:

```
PowerShell 7.1.3
Copyright © Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /Users/frios>
```

All is good until I start typing. I type 
d
and I get 
d$<5> 
then I type i and the d disappears and I get 
$<$<5>
then I type r and I get
$<5$<5>

If I then hit return I get the proper directory output on the screen but if the screen is full, the cursor jumps to mid screen.

Anyone seen this type of behavior before?

**Comment by migueldeicaza** [comment]
I did not set my shell to pwsh, but I tried logging into my machine with it, and could not reproduce it.

**Comment by frios** [comment]
Thank you. I am trying to figure out where the issue is occurring... is it a terminal issue or something else in the chain. It does happen consistently when I use SwiftTerm library in my iOS app to log into any server that has pwsh as its default shell: Windows, Mac or Ubuntu (Arm or X86-64). It is an input issue; i.e. it only occurs to characters I type. The interesting thing is that as far as I recall, this used to work fine at the end of last year. Any suggestions where I should start debugging to see if I can figure this out?

Thank you.

**Comment by migueldeicaza** [comment]
I would suggest that you log all the data that you receive and send, so you can take a look at what is going on.

One possibility is that you are not passing an environment to the remote site that allows it to operate, perhaps something like the TERM variable not been passed, or some other expectation is not really being met.

**Comment by frios** [comment]
I have traced my input and output through my ssh layer and through the terminal layer.
(I am using ipworksSSH as my ssh layer)

I am setting the terminal type to vt100.

When I connect to a pwsh terminal, then I type the letter d, I get back in my ssh layer's stdOut method

[93md
[37m
[0m
[24;19H$<5>

I can see the d at the end of the first line, then a bunch of control sequences. I pass all of this from my ssh layer to a TerminalView instance's feed method as a byteArray. I assume that the control sequences would be eventually handled by the parser.parse method. Is that not correct?

**Comment by migueldeicaza** [comment]
I tried setting up an account, with pwsh, but when I do, and I try doing sudo to it, I get:

"/usr/loca/bin/pwsh: no such file or directory"

Even if it is there, and I have execute permissions.

**Comment by frios** [comment]
OK so I have a break point in my SSH onStdOut function. When I type the letter d I get on the first break:

1b 5b 39 33 6d 64 ( this should be setting the foreground to yellow and typing the d)

I hit continue and I get

1b 5b 33 37 6d 1b 5b 30 6d (sets a white foreground, then default foreground)

I hit continue again and I get

1b 5b 32 34 3b 31 39 48 24 3c 35 3e (no underline and some other stuff)

Then its done for that input.


Esc sequence interpretations from here: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

**Comment by frios** [comment]
> I tried setting up an account, with pwsh, but when I do, and I try doing sudo to it, I get:
> 
> "/usr/loca/bin/pwsh: no such file or directory"
> 
> Even if it is there, and I have execute permissions.

On an Ubuntu server, mine is located at /usr/bin/pwsh

**Comment by migueldeicaza** [comment]
I setup an Ubuntu machine to try this, and it works fine:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/36863/115046397-65d23700-9ea5-11eb-90a1-a7c1b37e0408.png">

I am using the iOS sample in the project

**Comment by migueldeicaza** [comment]
The 3c 35 3e sequence being "<5>" is not part of xterm/vt100 infocmp, so I suspect that you have the wrong TERM value.

What is the TERM value?

Try running this:
```
PS /home/pwsh> env
```

**Comment by frios** [comment]
The Term value is TERM=xterm-256color

**Comment by frios** [comment]
OK, I set my SSH layer to xterm-256color and that definitely fixes the weird character problem!  Thank you for the help. I still have another issue, but I will attempt to figure out what is going on first, I think it might be a terminal size issue.

But thank you!

**Comment by migueldeicaza** [comment]
Great news!
