### ISSUE TITLE
Incorrect Emacs rendering in horizontal split

### ISSUE THREAD

**Issue by st3fan** [migueldeicaza/SwiftTerm#171]
I'm having pretty great success with SwiftTerm but there is one app that is not rendered properly: when I run Emacs within SwiftTerm, it's layout is a bit off when I `M-x help` in a wide terminal so that you get a side by side split.

I've set the terminal to `xterm-256color` and `xterm` but that doesn't seem to make a difference.

The only hint I have is that SwiftTerm prints

```
Info: Unhandled Window command: [22, 0, 0]
Info: Unhandled Window command: [23, 0, 0]
```

What is the best place to lookup these codes? Maybe handling these commands is this is an improvement I can contribute?

> Update: Note that the `Unhandled Window command ` may be a red herring - I don't think it is happening during rendering. See comments.

<img width="1386" alt="Screen Shot 2021-04-14 at 4 57 56 PM" src="https://user-images.githubusercontent.com/28052/114778248-9b124400-9d42-11eb-8437-3f027aa7ce38.png">

**Comment by st3fan** [comment]
Hmm looking again at this, now I am not actually sure if the `Unhandled Window command` output is happening during the above rendering.

**Comment by st3fan** [comment]
Oh I found out something interesting. Initially the rendering is incorrect, but when I resize the window it re-renders correctly. In the case below I make the terminal one column less wide:

<img width="1389" alt="Screen Shot 2021-04-14 at 5 16 05 PM" src="https://user-images.githubusercontent.com/28052/114780350-46bc9380-9d45-11eb-9aaf-af56f3b456bd.png">
<img width="1368" alt="Screen Shot 2021-04-14 at 5 16 16 PM" src="https://user-images.githubusercontent.com/28052/114780353-47edc080-9d45-11eb-92f8-048b88116252.png">

**Comment by st3fan** [comment]
I think this issue is invalid - the resize issue is most likely an application error, not a SwiftTerm issue.

**Comment by migueldeicaza** [comment]
Are you using something like tmux or screen?

Those commands are sent to set the window title, they contain an additional zero, I should look into whether that is acceptable.   How can I reproduce that problem?

I would need the version of Emacs, and any terminal software you are using, as well as the TERM environment variable.

**Comment by migueldeicaza** [comment]
Oh, I see, if I have a big enoug Emacs, I also get this misrendering.

Thanks for reporting, I will investigate.

I do not think the Window commands are the problem.

**Comment by lvht** [comment]
It also cannot render in tmux vertical split.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/2030591/116184798-0997ce80-a753-11eb-889f-7347072ec21c.png">

**Comment by migueldeicaza** [comment]
Ok figured it out - I used a wrong default ("convert new lines into new-line + carriage return") setting some long time ago.

This should be fixed, not sure about the second, as I have never used tmux.
