### ISSUE TITLE
Mac: Out of sync state

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTerm#184]
There is a condition where the attributes get out of sync with the contents, it looks like a cache.

```
#!/bin/bash

for r in `yes | head -300`; do
for y in 41 42 43 44 45 46 47; do
    printf "\e[${y}m"
    for x in 31 32 33 34 35 36 37; do
	printf "\e[${x}mA"
    done
done
printf "\e[0m"
done
```

Save the output to a file and run it, rather than clearing the attributes, this keeps the last set of attributes.   Clearing the screen with C-l and then showing the last 900 bytes out of the above file (dd if=f skip=1 bs=90000) show that the attributes being rendered are wrong. (they should have a background, but do not).

Also, another artifact, after "cat" the output of the first file, some of the positions of the background cells are out of sync with the text.

**Comment by ios-52** [comment]
[Archive 2.zip](https://github.com/migueldeicaza/SwiftTerm/files/11079308/Archive.2.zip)

**Comment by migueldeicaza** [comment]
I believe this is fixed in the recent killing of the bad cache, but will confirm
