### ISSUE TITLE
shared and open are unavailable build 1.0.7

### ISSUE THREAD

**Issue by frios** [migueldeicaza/SwiftTerm#193]
I just updated to the latest build (I assume its 1.0.7) and am receiving the following error messages when building

```
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

and 

'open(_:options:completionHandler:)' is unavailable in application extensions for iOS
```

at the following location

```
    public func requestOpenLink (source: TerminalView, link: String, params: [String:String])
    {
        if let fixedup = link.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) {
            if let url = NSURLComponents(string: fixedup) {
                if let nested = url.url {
                    UIApplication.shared.open (nested)
                }
            }
        }
    }
```
at the line UIApplication.shared.open(nested)

This is an iOS app.

**Comment by migueldeicaza** [comment]
You installed Xcode beta 3;  this as far as I can tell is a regression on Xcode.  I have reported this, but haven't heard anything back from Apple

**Comment by frios** [comment]
OK. Thank you. I will keep an eye on this.

**Comment by migueldeicaza** [comment]
I think it is possible that I had a problem all along, but I tried changing the obvious setting "Require Only App-Extension-Safe API" set to NO, and then tried setting to YES, then setting it back to NO with no difference.

It always end up passing the `-application-extension` to the compiler.   Perhaps I messed the configuration elsewhere?

**Comment by migueldeicaza** [comment]
I temporarily moved the code to the application to work around this issue, so it should build for now, and will undo this when Xcode gets fixed.
