### ISSUE TITLE
Indexed background colors are broken

### ISSUE THREAD

**Issue by MyDanny** [migueldeicaza/SwiftTerm#197]
This shell command should produce some green text on yellow background, but it produces yellow text on the default background instead:

```
printf "\e[38;5;22m\e[48;5;222mHello\e[0m\n"
```

I believe this segment in Terminal.swift around line 3001 needs `fg` changed to `color` to fix this.

```swift
                case 5: // indexed color
                    if i+1 < parCount {
                        fg = Attribute.Color.ansi256(code: UInt8 (min (255, pars [i+1])))
                        i += 1
                    }
                    i += 1
```

**Comment by migueldeicaza** [comment]
Thank you!   You are absolutely right, a fix has been pushed.
