### ISSUE TITLE
Swapping values of variables

### ISSUE THREAD

**Issue by onowuy** [migueldeicaza/SwiftTerm#229]
In _Terminal.swift_ function **getSelectedLines**(p1: Position, p2: Position), the switch case at lines 4803-4805
```
    case .after:
        start = end
        end = start
```
seems odd, forcing _end_ value to _start_ instead of swapping them. Should we perhaps use a temp variable?
```
    case .after:
        let temp = start
        start = end
        end = temp
```

**Comment by JoeMatt** [comment]
swift atomics is cross platform, for a non blocking memory swap<
https://www.swift.org/blog/swift-atomics/

**Comment by migueldeicaza** [comment]
Thank you!   You are correct, this was a logic error, fixed
