### ISSUE TITLE
Need a hook to the terminal out to do processing

### ISSUE THREAD

**Issue by ayrtonsoftware** [migueldeicaza/SwiftTerm#276]
I have put the terminal in a larger window which keeps track of the current directory to display a finder like pane. Also, I am processing the terminal output to perform certain tasks. At this point I need to insert my code for each version. Any change to make it standard?

**Comment by migueldeicaza** [comment]
I am not sure which code you are inserting that you are referring to.

Feel free to start a discussion on the forums.
