### ISSUE TITLE
PageUp-PageDown Key not working

### ISSUE THREAD

**Issue by ios-52** [migueldeicaza/SwiftTerm#285]
Hello
can you please check page screen up-down not working on iOS and iPad

https://user-images.githubusercontent.com/123171606/227172210-6406d12a-2c5b-4a4e-b7ed-527e15061eeb.mov

**Comment by ios-52** [comment]
@migueldeicaza Any update?

**Comment by migueldeicaza** [comment]
Those keystrokes are intended to send the DEC page up and page down commands, so your application needs to be aware of those commands.   

I guess in the non-app mode it might be nice to scroll, but you might as well just swipe.

I might review a PR if you send it, but I am on the fence on changing that.
