### ISSUE TITLE
Mouse text selection gets broken after scrolling the first view

### ISSUE THREAD

**Issue by alealealedocebo** [migueldeicaza/SwiftTerm#306]
Hi,

I implemented SwiftTerm in my own app. I'm very new to Swift so I may raise a dumb issue.

I can select text with the mouse and use Copy-Paste shortcuts on LocalProcessTerminalView, they work flowlessly.
However, if I scroll down the View and select something that was rendered beyond the first view render, I get all the text selected each time instead of what I'm pointing to with the mouse.

Is there any callback I need to be aware of to recalculate the window render geometries?

![screen](https://github.com/migueldeicaza/SwiftTerm/assets/129745430/de73a0a8-4497-4ad0-80f1-af6a1483325d)

**Comment by migueldeicaza** [comment]
Sadly that looks like a bug in the Mac front-end for the Terminal.    There is another similar bug to this filed, I will try to take a look soon.

**Comment by alealealedocebo** [comment]
Thanks. Will you update this thread once done or is there another issue/ticket I should be aware of to track your activities in the matter?
