### ISSUE TITLE
ANSI escape codes do not render consistantly

### ISSUE THREAD

**Issue by tgb20** [migueldeicaza/SwiftTerm#314]
**Describe the bug**
ANSI escape codes are not showing colors consistently. 

**To Reproduce**
Send a message with the following contents to a terminal:
```
[31;1m[00:50:01 ERROR]: [91mThis is red This is also red! [92mThis is green [97mAnd this is white[0m
[m[00:50:01 INFO]: [91mThis is red This is also red! [92mThis is green [97mAnd this is white[0m
[33;1m[00:50:01 WARN]: [91mThis is red This is also red! [92mThis is green [97mAnd this is white[0m
```
The ? are escape characters, I am not sure how to share them properly

**Expected behavior**
All three lines are rendered with a different beginning log type and the same color text contents:

**Screenshots**

VSCode

![VSCode preview](https://github.com/migueldeicaza/SwiftTerm/assets/5331697/618d02ee-8732-4aea-86f0-4103ce66838e)

Xterm.js

![Xterm.js](https://github.com/migueldeicaza/SwiftTerm/assets/5331697/f85f8489-9633-4f96-8c99-1add4d9cca97)

SwiftTerm

![CleanShot 2023-07-06 at 20 53 42](https://github.com/migueldeicaza/SwiftTerm/assets/5331697/faee2187-e195-46b2-bed4-47c65416f745)

**Desktop (please complete the following information):**
- Xterm.js tested on Chrome 114.0.5735.198
- VSCode tested using [ANSI Colors](https://marketplace.visualstudio.com/items?itemName=iliazeus.vscode-ansi)

**Smartphone (please complete the following information):**
- SwiftTerm tested on iPhone 14 Pro Max Simulator running iOS 16.2
- SwiftTerm was also tested on various other iPhones with the same result

**Comment by migueldeicaza** [comment]
Perhaps this is your theme color you are using?

**Comment by tgb20** [comment]
I have not made any theme or rendering changes.

**Comment by migueldeicaza** [comment]
Thanks for the bug report, this was indeed my bug, but only got to my computer now.

Fixed.
