### ISSUE TITLE
Use canImport(UIKit)/canImport(AppKit) instead of os(iOS)/os(macOS)

### ISSUE THREAD

**Issue by osy** [migueldeicaza/SwiftTerm#319]
I think this would be useful for supporting other Apple platforms such as tvOS and visionOS. However, this would require Swift 4.1, so you probably need to add `swiftLanguageVersions: [.v4_2]` to Package.swift. I was going to make a PR but I didn't know if you actually want to support other platforms (since builds would be broken due to missing SDK features).

**Comment by migueldeicaza** [comment]
Good idea:
https://github.com/migueldeicaza/SwiftTerm/pull/321

**Comment by migueldeicaza** [comment]
tvOS and visionOS should work now.
