### ISSUE TITLE
`inputAccessoryView` and `inputAssistantItem` missing in latest visionOS SDK

### ISSUE THREAD

**Issue by osy** [migueldeicaza/SwiftTerm#327]
Trying to build on the latest visionOS SDK in Xcode 15.1 beta:

```
Cannot override 'inputAccessoryView' which has been marked unavailable
'inputAssistantItem' is unavailable in visionOS
```

This is weird because in UTM, we use `inputAccessoryView` without the override and it works fine. However, I don't know how to deal with `inputAssistantItem`.

**Comment by migueldeicaza** [comment]
Fixed by the above PR
