### ISSUE TITLE
CMD + K Should Clear Screen Contents

### ISSUE THREAD

**Issue by rehatkathuria** [migueldeicaza/SwiftTerm#345]
Similar to how the Terminal app in macOS clears its contents, the mac terminal view should clear its contents with the CMD + K keystroke. 

This behaviour is native on macOS and can also be witnessed in the console for Xcode

The alternative that currently exists is the CTRL + L keystroke which I believe is native to Unix as opposed to macOS

**Comment by migueldeicaza** [comment]
This is a client feature, not a feature of the library.

So folks that desire this behavior need to that themselves on their client app.
