### ISSUE TITLE
Combining characters

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTerm#67]
I suspect that the reason the UTF-8-Demo.txt regressed in spacing with the math symbols is my new approach at combining characters.

**Comment by migueldeicaza** [comment]
<img width="633" alt="Screen Shot 2020-04-12 at 12 27 00 AM" src="https://user-images.githubusercontent.com/36863/79060548-57c75600-7c54-11ea-9816-8e410b0ac46a.png">

**Comment by migueldeicaza** [comment]
Either that, or the recent font changes or the rendering changes.

**Comment by krzyzanowskim** [comment]
where do I find `UTF-8-Demo.txt`, is it in repository?
I found one here: https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt

**Comment by krzyzanowskim** [comment]
for the record Terminal.app is not perfect (for the same font), however significantly better than ours
<img width="179" alt="Screenshot 2020-04-13 at 11 31 34" src="https://user-images.githubusercontent.com/758033/79110271-5a23d000-7d7a-11ea-8ad5-b8ce654bf9cb.png">

**Comment by krzyzanowskim** [comment]
Xcode is closer to ours ;)

<img width="172" alt="Screenshot 2020-04-13 at 11 33 55" src="https://user-images.githubusercontent.com/758033/79110433-ad961e00-7d7a-11ea-804b-cc61ba2c1e3b.png">

**Comment by migueldeicaza** [comment]
And this is iTerm2:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/36863/79385571-cfd49b00-7f36-11ea-8ba9-3dd25dd9a752.png">

None seem perfect, I wonder if this works better on something like a Unicode text editor?

**Comment by migueldeicaza** [comment]
Neither Xcode, Emacs, TextEdit or VSCode render this remotely in an acceptable way either.

It really seems like iTerm and Terminal.app render this the best

**Comment by migueldeicaza** [comment]
Ook, I have a couple of theories now, and I do not think I am going to like them.

The bottom and top parts of the sigma character actually use three slots.   Why am I not going to like it?  Because every implementation of the "How many columns does this Unicode Rune take" (the `wcwidth` will  compute 1 or 2, or in this case, returns -1).   This means that even if the terminal renders it properly, almost every console app that deals with sizes will be broken in terms of rendering.   

I think I can peacefully wait for a resolution elsewhere.

**Comment by krzyzanowskim** [comment]
It sounds like rabbit hole

**Comment by krzyzanowskim** [comment]
for the reference. Comparison fixed height and calculated height result:

<img width="1729" alt="Screenshot 2020-04-17 at 13 00 36" src="https://user-images.githubusercontent.com/758033/79562517-8a85aa00-80ab-11ea-8ecd-60e5cab0a6e7.png">

**Comment by krzyzanowskim** [comment]
Notes:
I see two problems
1. **height** It should be fixed for the terminal, and draw higher symbols at the same time. Higher symbols should overlay the previous line.
2. **width** We want a fixed width, but width is not always the same. This one is tricky. Probably we have to layout glyphs manually (can't rely on `CTLineDraw`) character by character (not glyph by glyph) - at least that's next what I'll try.

**Comment by migueldeicaza** [comment]
With that pull request, the rendering looks glorious:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/36863/79671862-9f416b00-819b-11ea-99a3-6f581b053e64.png">

**Comment by 7ombie** [comment]
In the README, it says "Solid UTF-8 support, excellent rendering". This is followed by a screenshot of SwiftTerm failing the first test (pretty badly):

<img width="799" alt="80055786-95e43580-84f0-11ea-86dd-8dfb7f062b39" src="https://github.com/migueldeicaza/SwiftTerm/assets/80077603/dfe92063-69e5-471e-bb6b-86dca78275ec">

The two-column text should be aligned with the bar characters in the ruler above, but it's not even close.

It looks like a awesome project, but that example was confusing.

**Comment by migueldeicaza** [comment]
<img width="891" height="1699" alt="Image" src="https://github.com/user-attachments/assets/cb55eddb-ae96-417c-9fea-fb75faab2db2" />
<img width="891" height="1699" alt="Image" src="https://github.com/user-attachments/assets/ae468839-b8d2-402c-8174-d519a84647e1" />
