### ISSUE TITLE
"clear" mess up with scrolling position

### ISSUE THREAD

**Issue by krzyzanowskim** [migueldeicaza/SwiftTerm#69]
Reproduce crash:
1. fill enough lines to scroll the screen
2. run `clear` command. Notice scroller value vs what's on screen:

    <img width="695" alt="Screenshot 2020-04-13 at 02 09 02" src="https://user-images.githubusercontent.com/758033/79083025-c0cdcd00-7d2b-11ea-8a6b-f792817c6512.png">

3. resize window
💥

<details><summary>backtrace</summary>
<pre>
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Index out of range
    frame #0: 0x00007fff6fd5e380 libswiftCore.dylib`_swift_runtime_on_report
    frame #1: 0x00007fff6fdd8243 libswiftCore.dylib`_swift_stdlib_reportFatalErrorInFile + 211
    frame #2: 0x00007fff6fa9f1dd libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 525
    frame #3: 0x00007fff6fa9ecf7 libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 87
    frame #4: 0x00007fff6fa9e9c3 libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 99
    frame #5: 0x00007fff6fa9e5d5 libswiftCore.dylib`Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 533
    frame #6: 0x00007fff6fa7c28f libswiftCore.dylib`Swift._ArrayBuffer._checkInoutAndNativeTypeCheckedBounds(_: Swift.Int, wasNativeTypeChecked: Swift.Bool) -> () + 255
    frame #7: 0x00007fff6fa7fe8e libswiftCore.dylib`Swift.Array.subscript.getter : (Swift.Int) -> A + 78
  * frame #8: 0x000000010007f754 Stevedore`BufferLine.subscript.getter(index=84, self=0x000060000027e780) at BufferLine.swift:36:25
    frame #9: 0x00000001000de37e Stevedore`TerminalView.buildAttributedString(line=0x000060000027e780, cols=85, prefix="", self=0x00000001032f4bd0) at MacTerminalView.swift:460:36
    frame #10: 0x00000001000dfca1 Stevedore`TerminalView.fullBufferUpdate(self=0x00000001032f4bd0) at MacTerminalView.swift:496:35
    frame #11: 0x00000001000e714e Stevedore`TerminalView.frame.setter(newValue=(origin = (x = 10, y = 33), size = (width = 687, height = 590)), self=0x00000001032f4bd0) at MacTerminalView.swift:759:17
    frame #12: 0x00000001000e66e6 Stevedore`@objc TerminalView.frame.setter at <compiler-generated>:0
    frame #13: 0x00007fff33835235 AppKit`NSViewActuallyUpdateFrameFromLayoutEngine + 279
    frame #14: 0x00000001000e78a8 Stevedore`TerminalView.resize(oldSize=(width = 698, height = 631), self=0x00000001032f4bd0) at MacTerminalView.swift:782:15
    frame #15: 0x00000001000e791f Stevedore`@objc TerminalView.resize(withOldSuperviewSize:) at <compiler-generated>:0
    frame #16: 0x00007fff337d690d AppKit`-[NSView resizeSubviewsWithOldSize:] + 525
    frame #17: 0x00007fff337b1e31 AppKit`-[NSView setFrameSize:] + 2045
    frame #18: 0x00007fff3398faa9 AppKit`-[NSTabView setFrameSize:] + 142
    frame #19: 0x00007fff337c3c9e AppKit`-[NSView setFrame:] + 423
    frame #20: 0x00007fff33835235 AppKit`NSViewActuallyUpdateFrameFromLayoutEngine + 279
    frame #21: 0x00007fff337d690d AppKit`-[NSView resizeSubviewsWithOldSize:] + 525
    frame #22: 0x00007fff337b1e31 AppKit`-[NSView setFrameSize:] + 2045
    frame #23: 0x00007fff337c3c9e AppKit`-[NSView setFrame:] + 423
    frame #24: 0x00007fff33835235 AppKit`NSViewActuallyUpdateFrameFromLayoutEngine + 279
    frame #25: 0x00007fff337d96e0 AppKit`NSViewLevelLayout + 390
    frame #26: 0x00007fff337d954c AppKit`-[NSView layout] + 14
    frame #27: 0x00007fff337d8fea AppKit`_NSViewLayout + 600
    frame #28: 0x00007fff337d8a8e AppKit`-[NSView _layoutSubtreeWithOldSize:] + 388
    frame #29: 0x00007fff337d8be8 AppKit`-[NSView _layoutSubtreeWithOldSize:] + 734
    frame #30: 0x00007fff337d8be8 AppKit`-[NSView _layoutSubtreeWithOldSize:] + 734
    frame #31: 0x00007fff337d7e8d AppKit`-[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1121
    frame #32: 0x00007fff337d793e AppKit`-[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 148
    frame #33: 0x00007fff337d42e3 AppKit`-[NSWindow _oldPlaceWindow:fromServer:] + 744
    frame #34: 0x00007fff337d25d5 AppKit`-[NSWindow _setFrameCommon:display:fromServer:] + 1352
    frame #35: 0x00007fff33b5bcaf AppKit`-[NSWindow(NSWindowResizing) _resizeWithEvent:] + 2656
    frame #36: 0x00007fff33a31c36 AppKit`-[NSTitledFrame attemptResizeWithEvent:] + 177
    frame #37: 0x00007fff33a31917 AppKit`-[NSThemeFrame handleMouseDown:] + 294
    frame #38: 0x00007fff33acedd8 AppKit`-[NSThemeFrame mouseDown:] + 30
    frame #39: 0x00007fff339b4280 AppKit`-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4914
    frame #40: 0x00007fff3391ea81 AppKit`-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
    frame #41: 0x00007fff3391de29 AppKit`-[NSWindow(NSEventRouting) sendEvent:] + 349
    frame #42: 0x00007fff3391c1b4 AppKit`-[NSApplication(NSEvent) sendEvent:] + 352
    frame #43: 0x00007fff3376921f AppKit`-[NSApplication run] + 707
    frame #44: 0x00007fff3373aff6 AppKit`NSApplicationMain + 777
    frame #45: 0x000000010005a36d Stevedore`main at AppDelegate.swift:16:7
    frame #46: 0x00007fff70442cc9 libdyld.dylib`start + 1
</pre>
</details>

**Comment by migueldeicaza** [comment]
The scroll position issue is separate from this crash, this looks like the Cocoa view has been updated before the underlying terminal has been.

How do you reproduce this issue?  I have struggled to get the same (I got another different one, which I am wondering what to do about - it is the reflow code that I never like, and I think there is a better and simpler way of solving it than the current heuristic)

**Comment by krzyzanowskim** [comment]
I can't reproduce it any longer.
